# 라즈베리 파이 4 (64비트)에 최적화된 Debian Bookworm 이미지를 기반으로 합니다.
FROM balenalib/raspberrypi4-64-debian:bookworm

# 빌드에 필요한 각종 도구와 Qt6 라이브러리를 설치합니다.
RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    qt6-base-dev \
    qt6-declarative-dev \
    qt6-tools-dev-tools \
    qt6-multimedia-dev \
    libqt6multimedia6 \
    libqt6opengl6-dev \
    libqt6svg6-dev \
    libqt5x11extras5-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    cmake \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 컨테이너 안의 작업 폴더를 /project로 지정합니다.
WORKDIR /project

# 랩탑의 소스 코드를 컨테이너의 /project 폴더로 복사합니다.
COPY . .

# 컨테이너 안에서 프로그램을 빌드합니다.
RUN cmake . && make

# 컨테이너가 시작될 때 최종적으로 실행할 명령어를 지정합니다.
CMD ["./Head_U"]
